export default [
  "user-list",
  "user-store",
  "user-update",
  "user-delete",
  "ticket-list",
  "ticket-store",
  "ticket-update",
  "ticket-delete",
  "ticket-adjust",
  "role-list",
  "role-store",
  "role-update",
  "role-delete",
  "permission-list",
  "log-list",
];
